version: '3'
services:
  rest_server:
    image: restic/rest-server
    ports:
      - 3001:8000
    volumes:
      - /path/to/backups:/data
    restart: always
    environment:
      - OPTIONS=--append-only
    container_name: rest_server_achillebackups

  restic_safe_forget_server:
    image: restic-safe-forget-server
    ports:
      - 3002:8000
    volumes:
      - /path/to/backups:/rfs_repos
    environment:
      - RFS_API_KEY=passwd
    restart: always
    container_name: restic_safe_forget_server_achillebackups
